### ISSUE TITLE
Project documentation with Markdown

### ISSUE THREAD

**Issue by Maksym637** [Lv-739-TAQC/teach_ua_739#103]
Create project documentation. It must consist with such items :
1.) Short description of the automated site
2.) Project structure (e. g. : POM model with page factory, smth like that)
2.) Description of used technologies
3.) Description how to clone project and **properties** file
4.) 4.1 Commands for test execution
     4.2 Commands for allure execution
5.) Information links

**Comment by AnnaMatviienko** [comment]
Done
https://github.com/Lv-739-TAQC/teach_ua_739/pull/108
